package colesico.framework.rpc.teleapi;

/**
 * RPC client API used in autogenerated RPC clients to call remote services
 */
public interface RpcClient {

    String REQUEST_PARAM = "request";
    String SERVE_METHOD = "serve";

    /**
     * Adds extra parameters and call target
     */
    <R> RpcResponse<R> serve(RpcRequest request);
}
