= Hello World

== Maven

To build a simple application, you must first set up your Maven project.
This should be a regular JAR application with the framework dependencies.
The framework supports different HTTP servers, so you must specify which server you want to use.

[source,xml]
----
<dependencies>

    <!-- Colesico weblet module -->
    <dependency>
        <groupId>net.colesico.framework</groupId>
        <artifactId>colesico-weblet</artifactId>
        <version>${project.version}</version>
    </dependency>

    <!-- Colesico Fusion HTTP Server integration -->
    <dependency>
        <groupId>net.colesico.framework</groupId>
        <artifactId>colesico-fusionhttp</artifactId>
        <version>${project.version}</version>
    </dependency>

</dependencies>
----

Since the Colesico framework generates extra Java code, you must also attach an annotation processor to your compilation process:

[source,xml]
----
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>${maven-compiler-plugin.version}</version>
    <configuration>
        <annotationProcessorPaths>
            <!-- Framework annotation processors -->
            <path>
                <groupId>net.colesico.framework</groupId>
                <artifactId>colesico-weblet</artifactId>
                <version>${project.version}</version>
            </path>
        </annotationProcessorPaths>
    </configuration>
</plugin>
----

Also, all dependencies should be collected into the `target/lib` folder.
For this purpose, you can use the Maven Dependency Plugin:

[source,xml]
----
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-dependency-plugin</artifactId>
    <version>${maven-dependency-plugin.version}</version>
    <executions>
        <execution>
            <phase>package</phase>
            <goals>
                <goal>copy-dependencies</goal>
            </goals>
            <configuration>
                <includeScope>runtime</includeScope>
                <excludeArtifactIds>javapoet</excludeArtifactIds>
                <outputDirectory>${project.build.directory}/lib</outputDirectory>
            </configuration>
        </execution>
    </executions>
</plugin>
----

== Main

Define a `Main` class and a static `main` method that will be the starting point of your application.
Inside this method, you should build an instance of the <<../ioc.adoc#,Inversion of Control container>>, then obtain an HTTP server instance and start it.

[source,java]
----
public static void main(String[] args) {
    // Create IoC container instance, obtain HTTP server and start it.
    IocBuilder
        .create()
        .build()
        .instance(HttpServer.class)
        .start();
}

// Alternative, more verbose code
public static void main(String[] args) {
    // Build DI container instance
    final Ioc ioc = IocBuilder.create().build();

    // Obtain HTTP server from DI container
    HttpServer httpServer = ioc.instance(HttpServer.class);

    // Start HTTP server
    httpServer.start();
}
----

== Weblet

A *Weblet* is an HTTP request controller.
It acts like a regular Servlet but can handle multiple request URLs.

* Define a Weblet class that contains a method responsible for handling requests.
* Annotate the Weblet class with the `@Weblet` annotation.

[source,java]
----
@Weblet
public class HelloWeblet {

    // Corresponding URL: http://localhost:8080/hello-weblet/say-hello
    public String sayHello() {
        return "Hello World!";
    }
}
----

Every public method within a Weblet class is considered a request handler.
By default, the request URL is constructed based on the Weblet class simple name and the handler method name.
Java camelCase notation is automatically transformed into kebab-case notation.

It is possible to customize the request URI using the `@Route` annotation applied to:

* a package (inside `package-info.java`)
* a Weblet class
* a Weblet handler method

<<../router.adoc#, See Router module details>>

== Run the Application

Compile and run the application:

[source,bash]
----
java -jar helloworld.jar
----

Then open the URL http://localhost:8080/hello-weblet/say-hello in your browser to see the result.

== Hello World Application Source Code

See the full source code in the framework repository under the `#examples/helloworld-example#` section.