= Hello world

== Maven

To build simple application you must first to setup your maven project.
This should be a regular jar application with the framework dependencies.

Although the framework consists of many modules, to specify dependencies you can use an bundle module
that includes the most frequently used specific modules - colesico-bundle-web  (or colesico-bundle-sql, etc.).

Because the framework can support different http servers, you must specify which one  server you want to use.

[source,xml]
----
<dependencies>
        <!-- Colesico common modules bundle -->
        <dependency>
            <groupId>net.colesico.framework</groupId>
            <artifactId>colesico-bundle-web</artifactId>
            <version>${colesico.version}</version>
        </dependency>

        <!-- Colesico undertow integration -->
        <dependency>
            <groupId>net.colesico.framework</groupId>
            <artifactId>colesico-undertow</artifactId>
            <version>${colesico.version}</version>
        </dependency>

</dependencies>
----

Since colesico framework generates extra java code you also must to attach annotation processor to you compilation process:

[source,xml]
----
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>${maven-compiler-plugin.version}</version>
    <configuration>
        <annotationProcessorPaths>
            <!-- Framework annotation processors -->
            <path>
                <groupId>net.colesico.framework</groupId>
                <artifactId>colesico-bundle-web</artifactId>
                <version>${colesico.version}</version>
            </path>
        </annotationProcessorPaths>
    </configuration>
</plugin>
----

Also, all dependencies should be collected to the target/lib folder. For this purpose, you can use maven dependency plugin:

[source,xml]
----
 <plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-dependency-plugin</artifactId>
	<version>${maven-dependency-plugin.version}</version>
	<executions>
		<execution>
			<phase>package</phase>
			<goals>
				<goal>copy-dependencies</goal>
			</goals>
			<configuration>
				 <includeScope>runtime</includeScope>
                 <excludeArtifactIds>javapoet</excludeArtifactIds>
				 <outputDirectory>${project.build.directory}/lib</outputDirectory>
			</configuration>
		</execution>
	</executions>
</plugin>
----


== Main

Define "Main" class and "main" static method that be a start point of you application.
Inside that method you should build an instance of the <<../ioc.adoc#,inversion of control container>>,
then  obtain a http server instance and start it.

[source,java]
----

public static void main(String[] args) {

        // Create IoC container instance, obtain http server and start it.

        IocBuilder
          .create()
          .build()
          .instance(HttpServer.class)
          .start();

}

// Alternative more verbose code
public static void main(String[] args) {

        // Build DI container instance
        final Ioc ioc = IocBuilder.create().build();

        // Obtain http server from DI container
        HttpServer httpServer = ioc.instance(HttpServer.class);

        // Start http server
        httpServer.start();
}
----

== Weblet

*Weblet* is a http requests controller.  It acts like a regular Servlet but can handle multiple request urls.

* Define a weblet class that contains a  method that would be responsive for request handling.
* Annotate weblet class with @Weblet annnotation.

[source,java]
----
@Weblet
public class HelloWeblet {

    // Corresponding url: http://localhost:8080/hello-weblet/say-hello
    public HtmlResponse sayHello(){
        return HtmlResponse.of("Hello World!");
    }
}

----

Every public method within weblet class considered to be a request handler.
By default request url constructed based on weblet class simple name and handler method name.
Java camel case notation transformed to kebab-case notation.

It is possible to customize request uri with @Route annotation applied on :

* package (inside package-info.java)
* weblet class
* weblet handler method

<<../router.adoc#, See Router module details>>

== Run the Application

Compile and run the application:

[source]
----
java -jar helloworld.jar
----

Then browse the url  http://localhost:8080/hello-weblet/say-hello to see result.

== Hello World application source code

See full source code in the framework source code section #examples/helloworld-example#

