package colesico.framework.rpc.client;

import colesico.framework.rpc.teleapi.RpcRequest;
import colesico.framework.rpc.teleapi.RpcResponse;

/**
 * RPC client API used in autogenerated RPC clients to call remote services
 */
public interface RpcClient {

    String REQUEST_PARAM = "request";
    String SERVE_METHOD = "serve";

    /**
     * Adds extra parameters and call target
     */
    <R> RpcResponse<R> serve(String apiName, String methodName, RpcRequest request, Class<? extends RpcResponse<R>> responseType);
}
