package colesico.framework.beanvalidation;

import colesico.framework.dslvalidator.Command;
import colesico.framework.dslvalidator.DSLValidator;
import colesico.framework.dslvalidator.builder.AbstractValidatorBuilder;
import colesico.framework.dslvalidator.t9n.ValidatorMessages;

/**
 *  Basis for any bean validation builders prototypes
 *  generated by {@link ValidatorBuilderPrototype} annotation
 */
abstract public class BeanValidatorBuilder<V> extends AbstractValidatorBuilder {

    public static final String VALIDATE_METHOD = "validate";

    public BeanValidatorBuilder(ValidatorMessages msg) {
        super(msg);
    }

    /**
     * Root validation subject
     */
    public String subject() {
        return null;
    }

    /**
     * Returns bean validation flow.
     */
    abstract public Command<V> validate();

    /**
     * Builds bean validator
     */
    @SuppressWarnings("unchecked")
    public DSLValidator<V> build() {
        return validator(subject(), validate());
    }

}
