[[intro]]
= Colesico-HikariCP

HikariCP - Fast, simple, reliable.
HikariCP is a "zero-overhead" production ready JDBC connection pool.
This pool is the default pool used in the framework.

HikariCP pool can be configured with different ways.

== Default properties file

The easiest way to set up a pool is with the *hikari.properties* file.
This file may be located in a *./config* subdirectory of application working directory or in *META-INF* resource folder of application.
The framework will look for this file first in the directory and then in the resources.

To get DataSource configured with hikari.properties just inject it:

[source,java]
----

// Constructor
public MyService(DataSource ds){
   this.ds = ds;
}

----

TIP: HikariCP module defines the default data source for IoC.
To prevent this use HikariCPConditions.disableDefaultDataSource()

== Custom properties file(s)

In the case of working with several data sources, use different hikari properties files.

Define an extra config class with getFileName() method overriding:

[source,java]
----

@Config
public class ExtraHikariProperties extends HikariProperties {
    @Override
    protected String getFileName() {
        return "extra-hikari.properties";
    }
}

----

TIP: Here is also getDirectory() and getClassPath() methods can be overridden to chang properties file location.

After that create extra-hikari.properties file.

Then inject DataSource to your service with @Classed qualifier:

[source,java]
----

// Constructor
public MyService(@Classed(ExtraHikariProperties.class) DataSource ds){
   this.ds = ds;
}

----

Will be injected the data source with parameters from extra-hikari.properties file.

== Programmatic configuration

Programmatic configuration used when it is necessary to make flexible programmatic
configuration using the HikariConfig class.

Define config class implementation:

[source,java]
----

@Config
public class CustomHikariConfig extends HikariConfigPrototype{
    @Override
    public final HikariConfig getHikariConfig() {
        // Initialize and return HikariConfig object
    }
}

----

Then inject DataSource as usual to your service with @Classed qualifier:

[source,java]
----

// Constructor
public MyService(@Classed(CustomHikariConfig.class) DataSource ds){
   this.ds = ds;
}

----

== Examples

See full source code in the framework source code section #examples/jdbc-example#
