[[intro]]
= Colesico-IoC
:toc:
:toclevels: 5
:numbered:

== What is Colesico-IoC

Colesico-IoC is a simple, lightweight and fast dependency injection container for Java 25+.

== Key features

* Small codebase and great performance.
* Reflection is not used (code generation at compile time with AnnotationProcessor).
* Dependency injection is constructor-based only.
* Cyclic dependency resolving support (via `Provider`).
* Can be used as plugin-framework.
* Producers based instance creation configuration.
* Dependency injection configuration discovery at container start time (SPI based).
* Multiple dependency injection configurations support (e.g. for testing purpose).
* Out-of-the-box Singleton scope (single instance per container), Thread scope (instance per thread), Task scope (instance per task), RefreshScope support.
* Named injections support (`@Named` annotation).
* Classed injections support (`@Classed` annotation).
* Support for multiple dependency implementations (`@Polyproduce`).
* Injection point support (e.g. for Logger injection).
* Lifecycle listeners (`@PostConstruct`, `@PostProduce`).
* Optional injections (`@OptionalInject`).
* Conditional beans (`@Requires`).
* Bean substitution (`@Substitute`).
* JPMS compatible.

== Ioc container

The Ioc container is used to obtain instances with injected dependencies.

Ioc container can be created with the builder:

[source,java]
----
IocBuilder iocBuilder = IocBuilder.create();
----

Builder is not thread safe.
But Ioc container is thread safe and can be used in multithreaded environment.
To create IoC container from builder:

[source,java]
----
Ioc ioc = iocBuilder.build();
----

Or just:

[source,java]
----
Ioc ioc = IocBuilder.create().build();
----

Obtaining instances with injected dependencies is done using these methods:

* `instance()` - returns class instance.
* `provider()` - returns class instance provider (`jakarta.inject.Provider<>`), used for "deferred" instance obtaining/creation.
* `supplier()` - returns class instance supplier, used for "deferred" instance obtaining/creation with the ability to pass a message.
* `polysupplier()` - returns chain of class instance suppliers (`colesico.framework.ioc.production.Polysupplier<>`).

To specify what instance to return, use the "keys":

* `TypeKey` - allows to specify instance class.
* `NamedKey` - allows to specify instance class and the named label.
* `ClassedKey` - like `NamedKey` but instead of a string label uses any class.

[source,java]
----
MyBean defaultBean = ioc.instance(new TypeKey<>(MyBean.class));
MyBean namedBean = ioc.instance(new NamedKey<>(MyBean.class, "AnyName"));
MyBean classedBean = ioc.instance(new ClassedKey<>(MyBean.class, AnyClass.class));
----

When injecting dependencies to a constructor each key corresponds to a specific annotation:

* `TypeKey` - no annotation.
* `NamedKey` - `@Named`.
* `ClassedKey` - `@Classed`.

[source,java]
----
public class MyBeanHolder {

    private final MyBean defaultBean;
    private final MyBean namedBean;
    private final MyBean classedBean;

    public MyBeanHolder(MyBean defaultBean,
                       @Named("AnyName") MyBean namedBean,
                       @Classed(AnyClass.class) MyBean classedBean) {

        this.defaultBean = defaultBean;
        this.namedBean = namedBean;
        this.classedBean = classedBean;
    }
}
----

To obtain an instance from the Ioc container, you can specify just an instance class (it will be implicitly converted to `TypeKey`):

[source,java]
----
MyBean defaultBean = ioc.instance(MyBean.class);
----

== Qualifications

By default IoC uses the following qualifiers to disambiguate dependency injection:

* `@Named` - allows you to qualify a dependency using an any string name.
* `@Classed` - the same as `@Named` but instead of a text name, it uses an arbitrary class.

== Producers

The IoC container "finds out" about classes for dependencies injection with the producers.
Producer defines the instance creation way.
Producer is a plain java class annotated with `@Producer` annotation.

Creating an instance of a class is defined in two ways:

* Add `@Produce` annotation on a producer class.
* Define producer's public method.

`@Produce` annotation specifies an instance class.
In this case, the IoC container will instantiate the instance simply by calling:
`new MyClass(param1, paramN);`

If custom logic is needed to create an instance, define a public producer method that should return the instance.
All public methods of the producer are considered as provider-methods of instances of classes and used by the IoC container for creating instances.

Producer example:

[source,java]
----
@Producer
@Produce(MyImplementation.class)
@Produce(MyClass.class)
public class MyProducer {

    // Produce instance of MyInterface (MyImplementation implements MyInterface) 
    @Singleton
    public MyInterface getMyInstance(MyImplementation impl){
        return impl;
    }

    // Produce instance for named dependency
    @Named("mynamed")
    public MyInterface getMyNamedInstance(MyImplementation impl){
        return impl;
    }
    
    // Manual instance creation MyBean
    public MyBean getMyBean(MyClass dependency1, MyInterface dependency2){
        return new MyBean(dependency1, dependency2);
    }
}
----

== Implementations

There are two ways to work with implementations:

. Through the producer's producing method.
. Using `@KeyType` annotation (or `@Produce.keyType`).

[source,java]
----
@Producer
@Produce(MyImplementation.class)
public class MyProducer {

    public MyInterface getMyImpl(MyImplementation impl){
        return impl;
    }
}
----

or with `keyType` feature:

[source,java]
----
@Producer
@Produce(value = MyImplementation.class, keyType = MyInterface.class)
public class MyProducer {
}
----

This producer will produce `MyInterface` object implemented by `MyImplementation` class.
In this case the object can be obtained from the container by `MyInterface` type only:
`ioc.instance(MyInterface.class)`.

Attempt to use `ioc.instance(MyImplementation.class)` will cause `UnsatisfiedInjectionException`.
To allow that obtaining, add `MyImplementation.class` itself to `keyType` list.

== Polyproducing

`@Polyproduce` annotation allows to specify that the IoC container may supply multiple instances for the dependency.
If this annotation is not applied to the producer method, an attempt to define more than one instance producer (for the same class) will fail with ambiguous dependency error.

The `@Polyproduce` annotation has an `order` parameter (default `0`) that defines the order of factories in the `Polysupplier` chain. Lower values have higher precedence.

[source,java]
----
@Producer
public class MyProducer {

    public MyInterface getMyInstance1(MyImpl1 impl){
        return impl;
    }

    // This is ambiguous producing of MyInterface
    public MyInterface getMyInstance2(){
        return new MyImpl2();
    }

    @Polyproduce
    public MyBean getMyBean1(MyBeanImpl impl){
        return impl;
    }

    // No ambiguous producing because of @Polyproduce
    @Polyproduce(order = 1)
    public MyBean getMyBean2(){
        return new MyBeanImpl2();
    }
}
----

== Scopes

The framework out-of-the-box supports the following scopes of instances:

* `@Singleton` - so-called local singleton. One instance of class per IoC container.
* `@ThreadScoped` - one instance per thread.
* `@TaskScoped` - one instance per task (using `ScopedValue`, Java 21+).
* `@RefreshScoped` - singleton-like but allows recreation of beans on demand.
* `@Unscoped` - no scope defined for instance (default).

To define the instance scope you must specify a scope annotation either on the instance class or on the producer provider-method.

=== Singleton

This scope supports one instance per IoC container (local singleton).

Example:

[source,java]
----
@Singleton
public class MyBean1 {}

public class MyBean2 {}

@Producer
@Produce(MyBean1.class)
public class MyProducer{
   
   @Singleton
   public MyBean2 getMyBean2(){
      return new MyBean2();
   }
}
----

In this example the instances of both classes `MyBean1` and `MyBean2` are singletons.

=== Thread scope

This scope supports one instance per thread.
When the thread scope is used with threads from a thread pool, before using it in a thread retrieved from the pool, it is mandatory to call `ThreadScope.open()` on the scope instance and call `ThreadScope.close()` before returning the thread to the pool.

[source,java]
----
@ThreadScoped
public class ThreadScopedBean {
    private int counter = 0;
    public String getMessage() {
        return "ThreadScoped-" + (counter++);
    }
}
----

Usage:

[source,java]
----
ThreadScope threadScope = ioc.instance(ThreadScope.class);
threadScope.forTask(() -> {
    // Inside this block, @TaskScoped beans are bound to this task
    ThreadScopedBean bean = ioc.instance(ThreadScopedBean.class);
    // ...
});
----

=== Task scope

This scope supports one instance per task using Java's `ScopedValue` (available since Java 21).
The scope is active only within a `TaskScope.forTask(Runnable)` block.

[source,java]
----
@TaskScoped
public class TaskScopedBean {
    // ...
}
----

Usage:

[source,java]
----
TaskScope taskScope = ioc.instance(TaskScope.class);
taskScope.forTask(() -> {
    // Inside this block, @TaskScoped beans are bound to this task
    TaskScopedBean bean = ioc.instance(TaskScopedBean.class);
    // ...
});
----

=== Refresh scope

Refresh scope is similar to singleton, but allows recreating beans on demand by invoking `RefreshScope.refresh()`.
This could be useful, for example, to implement reloading configuration without application restarting.

[source,java]
----
@RefreshScoped
public class ConfigBean {
    private String configValue;

    public String getConfigValue() { return configValue; }
    public void setConfigValue(String value) { this.configValue = value; }
}
----

Usage:

[source,java]
----
RefreshScope refreshScope = ioc.instance(RefreshScope.class);
ConfigBean config = ioc.instance(ConfigBean.class);

// ... later, to reload:
ConfigBean newConfig = refreshScope.refresh(ConfigBean.class);

// or refresh all:
refreshScope.refreshAll();
----

=== Unscoped

An instance of the class associated with `@Unscoped` annotation will be created each time it is requested from the IoC container.
This is the default "scope" when no scope is explicitly defined.

== Injectable constructors

Classes for dependency injection may not have an explicitly defined constructor.
IoC container will use the default constructor to create instances.
If more than one constructor is declared, the one that will be used for dependency injection must be annotated with `@Inject`, otherwise the IoC container will use the first one in the class.
If the constructor is the only one, the `@Inject` annotation is optional.

The constructor parameters can be annotated with `@Named`, `@Classed` annotations (for named/classed dependencies).

== Field/properties based injection

This kind of injection is not supported.

== Messages

[[messages]]
The messages are an instance supplying conception when it is possible to pass any object as a parameter for instance creation.
For example, this may be used for Logger creation with passing an `InjectionPoint` information.

To obtain a message in a producing method use the `@IocMessage` annotation:

[source,java]
----
@Producer
public class MyProducer{

   public MyBean getMyBean(@IocMessage MyMessage message){
      return new MyBeanImpl(message);
   }

}
----

To pass a message for instance creation use the `Supplier<T>`:

[source,java]
----
public class MainBean {
    private final ReceiverBean receiver;

    public MainBean(Supplier<ReceiverBean> receiverSup) {
        TextMessage msg = new TextMessage("Hello");
        this.receiver = receiverSup.get(msg);
    }
}
----

Or with IoC directly:

[source,java]
----
MyMessage message = new MyMessage(...);
MyBean myBean = ioc.instance(new TypeKey<>(MyBean.class), message);
----

== Injection point

In some cases it is useful to know the target class where the dependency is injected.
For example, it can be required for Logger injection.
To pass Injection point information to dependency producer use the `@Contextual` annotation, and to obtain that Injection point in the producer use the `@IocMessage` annotation and `InjectionPoint` type parameter.

Example:

[source,java]
----
@Producer
public class LogProducer {

    public Logger getLogger(@IocMessage InjectionPoint ip) {
        return LoggerFactory.getLogger(ip.targetClass());
    }
}

@Service
public class ServiceBean {
    final Logger logger;

    @Inject
    public ServiceBean(@Contextual Logger logger) {
        this.logger = logger;
    }
}
----

== Optional injections

To specify an optional injection, use the `@OptionalInject` annotation on the constructor parameter.
If the dependency is not found, `null` will be injected.

[source,java]
----
public class MyBean {
    private final OptionalDependency dep;

    public MyBean(@OptionalInject OptionalDependency dep) {
        this.dep = dep;
    }
}
----

== Lifecycle listeners

IoC container supports the following lifecycle listeners:

* `@PostConstruct` - invoked after a bean has been created and post produce listener has been invoked.
* `@PostProduce` - should be applied to a public producer method to declare a post produce listener. Invoked to handle just produced instance.

=== Listeners control

By default, for the default producing (`@Produce`) post produce lifecycle listeners invocation is disabled and post construct is enabled.
For the producing methods, all listener invocations are disabled.
To enable listeners invocation for a specific instance use `@ListenersControl` annotation on the producing method or `@Produce.postProduce`/`postConstruct` on default producing declarations.

=== @PostProduce

Post produce listener is invoked before `@PostConstruct` listener.
Post produce listener method should accept producing instance as a message and return the same instance (or substituted).

Example:

[source,java]
----
@Producer
@Produce(value = MainBeanLFC.class, postProduce = true)
public class LifecycleProducer {

    @PostProduce
    public MainBeanLFC postProduce(@IocMessage MainBeanLFC instance) {
        instance.setValue("Value");
        return instance;
    }
}
----

=== @PostConstruct

Post construct listener is invoked by IoC container after the instance has been created.
To define a listener, add `@PostConstruct` annotation on any no-params public instance class method.

[source,java]
----
public class MainBeanLFC {
    private String value;

    @PostConstruct
    public void init() {
        value = value + "Init";
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
----

== Circular dependencies

In case of circular dependencies use `Provider<Type>` instead of direct instance injection.

[source,java]
----
public class CircularA {
    private final Provider<CircularB> bProvider;

    public CircularA(Provider<CircularB> bProvider) {
        this.bProvider = bProvider;
    }
}
----

== Conditional beans

To define a conditional instance producing (for example for test cases) use `@Requires` annotation.
It allows to specify a condition checking class to be used to make a decision to include producing factory in the IoC container (whether to use the given producing method or not).

Condition checking class is a class that implements `colesico.framework.ioc.conditional.Condition` interface.
Its `isMet(ConditionContext context)` method is invoked by IoC builder to determine whether a given producing factory should be involved or not.

Example:

[source,java]
----
@Producer
@Produce(RegularBean.class)
@Produce(TestBean.class)
public class ConditionalProducer {

    @Requires(CustomCondition.class)
    public IBean getRegBean(RegularBean impl) {
        return impl;
    }

    @Requires(TestCondition.class)
    public IBean getTestBean(TestBean impl) {
        return impl;
    }
}
----

=== Condition context

Condition context is used to pass any value to condition checking beans.
Those values can be used to make a decision.
Condition context values can be set with `IocBuilder.getConditionContext().setAttribute()` method.

Condition checking beans for storing state can use not only the context but also static variables.

Example:

[source,java]
----
public class CustomCondition implements Condition {

    private static boolean enabled = false;

    public static synchronized void enable() {
        enabled = true;
    }

    public static synchronized void disable() {
        enabled = false;
    }

    @Override
    public boolean isMet(ConditionContext context) {
        return enabled;
    }
}
----

== Bean substitution

It is possible to override existing beans to customize behaviour for testing purposes or plugin support.
IoC module provides an explicit `@Substitute` annotation, which allows to specify bean replacement and integrates with support for Conditional Beans.

[source,java]
----
@Producer
@Produce(CustomBean.class)
public class CustomBeanProducer {

    @Substitute
    public BeanInterface getPlugin(CustomBean impl) {
        return impl;
    }
}
----

`@Substitute` annotation allows specifying *substitution rank* via `Substitution` enum:

* `STUB` (-1) - for stub instance production.
* `REGULAR` (0) - default rank when no `@Substitute` is specified.
* `DEFAULT` (1) - default rank for `@Substitute`.
* `EXTENSION` (2) - for plugins/extensions that replace regular functionality.
* `TEST` (3) - for testing purposes.

Higher ranks have precedence over lower ranks to perform substitution.

== Maven pom.xml

Specify dependency:

[source,xml]
----
<dependency>
    <groupId>net.colesico.framework</groupId>
    <artifactId>colesico-ioc</artifactId>
    <version>${colesico.version}</version>
</dependency>
----

Specify annotation processor:

[source,xml]
----
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <configuration>
        <annotationProcessorPaths>
            <path>
                <groupId>net.colesico.framework</groupId>
                <artifactId>colesico-ioc</artifactId>
                <version>${colesico.version}</version>
            </path>
        </annotationProcessorPaths>
    </configuration>
</plugin>
----

== Run an application with plugins discovery at startup

IoC container discovers producers with `ServiceLoader`.
If the application consists of several files (in `lib/*` dir.), and other files (e.g. plugins, modules etc) will be added later without rebuilding the main project, in order for the IoC container to discover all providers in these separate jar files, run the application with a command:

[source,bash]
----
java -cp lib/*:myapp-1.0.jar my.app.Main
----

When run by a command like:

[source,bash]
----
java -jar myapp-1.0.jar
----

IoC producers in external jar files in the folder `lib/*` that are added without rebuilding the project will not be discovered.

== Examples

See full source code in the framework source code section `#examples/ioc-example/`.
