[[intro]]
= Colesico-IoC
:toc:
:toclevels: 5
:numbered:

== What is Colesico-IoC

Colesico-IoC is a simple, lightweight and fast dependency injection container for Java 14 and above.

== Key features

* Small codebase and great performance.
* Reflection is not used (code generation at compile time with AnnotationProcessor).
* Dependency injection is constructor-based only.
* Cyclic dependency resolving support.
* Can be used as plugin-framework.
* Producers based instance creation configuration.
* Dependency injection configuration discovery at container start time (SPI based).
* Multiple dependency injection configurations support (e.g. for testing purpose).
* Out-of-the-box Singleton scope(single instance per container), Thread scope (instance per thread) support.
* Named injections support (@Named annotation).
* Classed injections support (@Classed annotation).
* Support for multiple dependency implementations (@Polyproduce).
* Injection point support (e.g. for Logger injection).
* Lifecycle listeners (@PostConstruct, @PostProduce)
* JPMS compatible

== Ioc container

The Ioc container is used to obtain instances with injected dependencies.

Ioc container can be created with the builder:

[source,java]
----
IocBuilder iocBuilder = IocBuilder.create();
----

Builder is not thread safe.
But Ioc container is thread safe and can be used in multithreaded environment.
To create IoC container from builder:

[source,java]
----
Ioc ioc = iocBuilder.build();
----

Or just:

[source,java]
----
Ioc ioc = IocBuilder.create().build();
----

Obtaining instances with injected dependencies is done using these methods:

* instance - returns class instance
* provider - returns class instance provider (javax.inject.Provider<>), is used to "deferred" instance obtaining/creation.
* supplier - returns class instance supplier, is used to "deferred" instance obtaining/creation with the ability to pass
  a  <<messages,message>>.
* polysupplier - returns chain of class instance suppliers (colesico.framework.ioc.production.Polysupplier<>)

To specify what instance to return, use the "keys":

* TypeKey - allows to specify instance class.
* NamedKey - allows to specify instance class and the named label
* ClassedKey - this is like the NamedKey but instead of a string label is used any class.

[source,java]
----
  MyBean defaultBean = ioc.instance(new TypeKey(MyBean.class), null);
  MyBean namedBean = ioc.instance(new NamedKey(MyBean.class,"AnyName"), null);
  MyBean classedBean = ioc.instance(new ClassedKey(MyBean.class, AnyClass.class), null);
----

When injecting dependencies to a constructor each key corresponds to a specific annotation:

* TypeKey - no annotation.
* NamedKey - @Named
* ClassKey - @Classed

[source,java]
----
public class MyBeanHolder {

    private final MyBean defaultBean;
    private final MyBean namedBean;
    private final MyBean classedBean;

    public MyBeanHolder(MyBean defaultBean,
                       @Named("AnyName") MyBean namedBean,
                       @Classed(AnyClass.class) MyBean classedBean) {

        this.defaultBean = defaultBean;
        this.namedBean = namedBean;
        this.classedBean = classedBean;
    }
}
----

In the particular case to obtaining an instance from the Ioc container, you can specify just an instance class. (it will be implicitly converted to TypeKey)

[source,java]
----
  MyBean defaultBean = ioc.instance(new TypeKey(MyBean.class),null);
  // OR:
  MyBean defaultBean = ioc.instance(MyBean.class);
----

== Qualifications

By default IoC uses the following qualifiers to disambiguate dependency injection:

* @Named - allows you to qualify a dependency using an any string name
* @Classed - the same as @Named but instead of a text name, it uses an arbitrary class

== Producers

The IoC container "finds out" about classes for dependencies injection with the producers.
Producer defines the instance creation way.
Producer is a plain java class annotated with @Producer annotation.

Creating an instance of a class is defined in two ways:

* Add @Produce annotation on a producer class.
* Define producer's public method.

@Produce annotation specifies an instance class.
In this case, the Ioc container will instantiate the instance simply by calling:
new MyClass (param1, paramN);

If need a custom logic to create an instance, define a public producer
method that should return the instance.
All public methods of the producer considered as a
provider-methods of instances of classes and used by the Ioc container
for creating instances.

Producer example:

[source,java]
----
@Producer
@Produce(MyImplementation.class)
@Produce(MyClass.class)
public class MyProducer {

    // Produce instance of MyInterface  (MyImplementation implements MyInterface) 
    @Singleton
    public MyInterface getMyInstance(MyImplementation impl){
        return impl;
    }

    // Produce instance for named dependency
    @Named("mynamed")
    public MyInterface getMyNamedInstance(MyImplementation impl){
        return impl;
    }
    
    // Manual instance creation MyBean
    public MyBean getMyBean(MyClass dependency1, MyInterface dependency2){
        return new MyBean( dependency1, dependency2);
    }
}
----

== Implementations

There are two ways to work with implementations:

. Through the producer's producing method
. Using @KeyType annotation  (or @Produce.keyType)

[source,java]
----
@Producer
@Produce(MyImplementation.class)
public class MyProducer {

    public MyInterface getMyImpl(MyImplementation impl){
        return impl;
    }
}
----

or with keyType feature:

[source,java]
----
@Producer
@Produce(value = MyImplementation.class, keyType = MyInterface.class)
public class MyProducer {
}
----
This producer will produce MyInterface object implemented by MyImplementation class.
In this case the object can be obtained from the container by MyInterface type only:
i.e. ioc.instance(MyInterface.class).

Attempt to use ioc.instance(MyImplementation.class) will cause UnsatisfiedInjectionException.
To allow that obtaining add MyImplementation.class itself to keyType list.

== Polyproducing

@Polyproduce annotation allows to specify that the IoC container may supply multiple instances for the dependency.
If this annotation is not applied to the producer method an attempt to define more than one instance producers (for the same class) will fails with ambiguous dependency error.

[source,java]
----
@Producer
public class MyProducer {

    public MyInterface getMyInstance1(MyImpl1 impl){
        return impl;
    }

    // This is ambiguous producing of MyInterface
    public MyInterface getMyInstance2(){
        return new MyImpl2();
    }



    @Polyproduce
    public MyBean getMyBean1(MyBeanImpl impl){
            return impl;
    }

    // Here is no ambiguous producing because of @Polyproduce
    @Polyproduce
    public MyBean getMyBean2(){
        return new MyBeanImpl2();
    }

}
----

== Scopes

The framework out-of-the-box supports the following scopes of instances:

* @Singleton - so-called local singleton.
One instance of class per Ioc container.
* @ThreadScoped - one instance  per thread


To define the instance scope you must specify an scope annotation(@Singleton и др) either on the instance class or on the producer provider-method.

Example:

[source,java]
----

@Singleton
public class MyBean1 {}

public class MyBean2 {}

@Producer
@Produce(MyBean1.class)
public class MyProducer{
   
   @Singleton
   public MyBean2 getMyBean2(){
      return new MyBean2();
   }
}
----

In this example the Instances of both classes MyBean1 and MyBean2 are singletones.

=== Thread scope

When the thread scope is used with threads from a thread pool,
before using it in a thread retrieved from the pool,
it is  mandatory need call ThreadScope.init() on the scope instance
and  call ThreadScope.destroy() before returning the thread to the pool.

== Injectable constructors

Classes for dependency injection may not have an explicitly defined constructor.
Ioc container will use the default constructor to create instances.
If more than one constructor declared, the one that will be used for dependency
injection must be annotated with @Inject annotation, otherwise the Ioc container
will use the first one in the class.
If the constructor is the only, the @Inject annotation is optional.

The constructor parameters can be annotated with the @Named, @Classed annotations
(for named/classed dependencies)

== Field/properties based injection

This kind of injection is not supported.

== Messages
[[messages]]

The messages are an instance supplying conception when it is possible to pass any object
as a parameter for instance creation. For example this may be used for Logger
creation with passing an InjectionPoint information.

To obtain message in producing method use the @Message annotation:

[source,java]
----

@Producer
public class MyProducer{

   public MyBean getMyBean(@Message MyMessage message){
      return new MyBeanImpl(message);
   }

}
----

To pass message for instance creation use the Supplier<T>

[source,java]
----

  public constructor(Supplier<MyBean> myBeanSup){
        MyMessage message = new MyMessage(...);
        MyBean myBean = myBeanSup.get(message);
  }
  
----

Or with IoC directly:

----
  MyMessage message = new MyMessage(...);
  MyBean myBean = ioc.instance(new TypeKey(MyBean.class), message);
----

== Injection point

In some cases it is useful to know the target class where the dependency injected.
For example, it can be required for the Logger injection.
To pass Injection point information to dependency producer use a @Contextual annotation,
and to obtain that Injection point in the producer use a @Message annotation and
InjectionPoint type parameter.
See logger injection detail example in the ioc-example source code.

Example:

[source,java]
----
@Producer
public class LogProducer {

    public Logger getLogger(@Message InjectionPoint ip) {
        return LoggerFactory.getLogger(ip.getTargetClass());
    }
}


@Sevice
public class ServiceBean{
    final Logger logger;

    @Inject
    public ServiceBean(@Contextual Logger logger){
        this.logger = logger;
    }
}
----

== Lifecycle listeners

IoC container supports the following lifecycle listeners:

* Post construct.
The bean public method annotated with _@PostConstruct_ annotation will be
invoked by the IoC container after a bean has been created and post produce listener
been invoked.
* Post produce.
_@PostProduce_ annotation should be applied to public producer method to declare post produce listener.
The post produce listener invoked by the IoC container to handle just produced instance.

=== Listeners control

By default, for the default producing (_@Produce_) post produce life cycle listeners invocation is disabled
and post construct is enabled. For the producing methods all listener invocation are disabled.
To enable listeners invocation for a specific instance use _@ListenersControl_ annotation on the producing
method or _@Produce.postProduce/postConstruct_ on default producing declarations.

=== @PostProduce

Post produce listener invoked before @PostConstruct listener.
Post produce listener method should accept producing instance as message and return the
same instance (or substituted)

Example:

[source,java]
----
@Producer
public class ConfigProducer{

    ...

    @PostProduce
    public Config initUndertowConfig(@Message Config config) {
        config.setValue("OK");
        return config;
    }
}
----

=== @PostConstruct

Post construct listener invoke by IoC container after the instance has been created.
To define a listener add @PostConstruct annotation on any no-params public instance class method.

== Circular dependencies

In case of circular dependencies use Provider<Type> instead of direct instance injection.

[source,java]
----
  public constructor(Provider<T> dependencyProvider){
        ...
  }
----

== Conditional beans

To define a conditional instance producing (for example for test cases) use @Requires annotation.
It allows to specify condition checking class be used to make a decision to include producing factory to IoC Container.
(To use the given producing method or not)

Condition checking class is a class implements colesico.framework.ioc.conditional.Condition interface.
It's method isMet(ConditionContext context) invoked by IoC builder to determine should a given producing factory
to be involved or not.

Example:

[source,java]
----
@Producer
@Produce(TestBean.class)
public class ConditionalProducer {

    // This instance will only be created for an enabled test condition
    @Requires(TestCondition.class)
    public IBean getTestBean(TestBean impl) {
        return impl;
    }

}
----

=== Condition context

Condition context is used to pass any value to condition checking beans.
That values can be used to make a decision.
Condition context values can be set with *IoCBuilder.getConditionContext().setAttribute()* method

Condition checking beans for storing state can use not only the context but also static variables.

Example:

[source,java]
----
public class TestCondition implements Condition {

    private static boolean enabled = false;

    public static synchronized void enable() {
        enabled = true;
    }

    public static synchronized void disable() {
        enabled = false;
    }

    @Override
    public boolean isMet(ConditionContext context) {
        return enabled;
    }
}
----

== Bean substitution

It is possible to overriding existing beans to customize behaviour for testing purposes or a plugins support.
IoC module provides an explicit @Substitute annotation, which allows to specify bean replacement and integrates with support for Conditional Beans.

[source,java]
----

@Producer
@Produce(CustomBean.class)
public class CustomBeanProducer {

    @Substitute
    public BeanInterface getPlugin(CustomBean impl){
        return impl;
    }
}
----

TIP: @Substitute annotation allows specifying *substitution rank*  (substitution priority)

== Maven pom.xml

Specify dependence:

----
        <dependency>
            <groupId>net.colesico.framework</groupId>
            <artifactId>colesico-ioc</artifactId>
            <version>${colesico.version}</version>
        </dependency>
----

Specify annotation processor:

----
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                    <encoding>${project.build.sourceEncoding}</encoding>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>net.colesico.framework</groupId>
                            <artifactId>colesico-ioc</artifactId>
                            <version>${colesico.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>        
        
----

== Run an application with plugins discovering at startup.

Ioc container discovers producers with ServiceLoader.
If the application consists of several files (in lib/* dir.), and
another files (e.g. plugins, modules etc) will be added later without
rebuilding the main project, in order the IoC container can discover
the all providers in these separate jar files run the application with
a command:

----
java -cp lib/*;myapp-1.0.jar my.app.Main
----

When run by a command like:

----
 java -jar  myapp-1.0.jar
----

IoC producers in external jar files in the folder lib/* that added without rebuilding the project will not be discovered.

== Examples

See full source code in the framework source code section #examples/ioc-example#


