= JDBC integration module

This module provides support for using jdbc connection through IoC injection and support
for database transaction management with TransactionalShell (@Transactional annotation).

Typical usage within the service:

.MyService.java
[source,java]
----
@Service
public class MyService {

    private final Provider<Connection> connProv;

    @Inject
    public TheService(Provider<Connection> connProv) {
        this.connProv = connProv;
    }

    @Transactional
    public String update() {

       try (Statement stmt = connectionProv.get().createStatement()){
            stmt.executeUpdate();
       }  catch (SQLException e) {
           // ...
       }

        // No need to commit transaction and close connection
    }
}
----

== Setup default data source

To configure default datasource just create hikari.properties file.

.config/hikari.properties or META-INF/hikari.properties
[source,properties]
----
ataSourceClassName=org.postgresql.ds.PGSimpleDataSource
username=user
password=password
jdbcUrl=jdbc:postgresql://...
----

See details https://github.com/brettwooldridge/HikariCP#gear-configuration-knobs-baby[HikariCP docs]

== Setup multiple data sources

For each additional data source, make the following:

1) Create additional config class and override getFileName method

.ExtraHikariProperties.java
[source,java]
----
@Config
public class ExtraHikariProperties extends HikariProperties {
    @Override
    protected String getFileName() {
        return "extra-hikari.properties";
    }
}
----
2) Fill in config file extra-hikari.properties

.config/extra-hikari.properties or META-INF/extra-hikari.properties
[source,properties]
----
driverClassName=...
jdbcUrl=jdbc:...
----

3) Create IoC producer to produce extra JDBC transactional shell, connection and data source:

.ExtraJdbcProducer.java
[source,java]
----
/**
 * Typical jdbc producer for extra DS
 */
@Producer
public class ExtraJdbcProducer {

    public static final String EXTRA = "extra";

    /**
     * Define extra transactional shell to control transactions.
     */
    @Singleton
    @Named(EXTRA)
    public TransactionalShell getTransactionalShell(@Classed(ExtraHikariProperties.class) DataSource ds) {
        return new JdbcTransactionalShell(ds);
    }

    /**
     * Produce extra connection providing from extra transactional shell
     */
    @Unscoped
    @Named(EXTRA)
    public Connection getConnection(@Named(EXTRA) TransactionalShell txShell) {
        return ((JdbcTransactionalShell) txShell).getConnection();
    }

    /**
     * Optionally produce extra data source from extra TxShell
     */
    @Unscoped
    @Named(EXTRA)
    public DataSource getDataSource(@Named(EXTRA) TransactionalShell txShell) {
        return ((JdbcTransactionalShell) txShell).getDataSource();
    }
}
----

== Examples

See full source code in the framework source code section #examples/jdbc-example#


