= JDBC integration module

This module provides support for using jdbc connection through IoC injection and support
for database transaction management with TransactionalShell (@Transactional annotation).

Typical usage within the service:

.MyService.java
[source,java]
----
@Service
public class MyService {

    private final Provider<Connection> connProv;

    @Inject
    public TheService(Provider<Connection> connProv) {
        this.connProv = connProv;
    }

    @Transactional
    public String update() {

       try (Statement stmt = connectionProv.get().createStatement()){
            stmt.executeUpdate();
       }  catch (SQLException e) {
           // ...
       }

        // No need to commit transaction and close connection
    }
}
----

== Setup default data source

To configure default datasource create hikari.properties file.

.config/hikari.properties or META-INF/hikari.properties
[source,properties]
----
ataSourceClassName=org.postgresql.ds.PGSimpleDataSource
username=user
password=password
jdbcUrl=jdbc:postgresql://...
----

See details https://github.com/brettwooldridge/HikariCP#gear-configuration-knobs-baby[HikariCP docs]

== Setup second  data source

1) Create custom config class and override getFileName method

.CustomHikariProperties.java
[source,java]
----
@Config
public class SecondHikariProperties extends HikariProperties {
    @Override
    protected String getFileName() {
        return "second-hikari.properties";
    }
}
----
2) Fill in config file second-hikari.properties

.config/second-hikari.properties or META-INF/second-hikari.properties
[source,properties]
----
driverClassName=...
jdbcUrl=jdbc:...
----

3) Create IoC producer to produce JDBC transactional shell, connection and data source:

.JdbcProducer.java
[source,java]
----
@Producer
public class JdbcProducer {

    /**
     * Define transactional shell to control transactions.
     */
    @Singleton
    @Named("second")
    public TransactionalShell getTransactionalShell(@Classed(SecondHikariProperties.class) DataSource ds) {
        return new JdbcTransactionalShell(ds);
    }

    /**
     * Produce connection providing from second transactional shell
     */
    @Unscoped
    @Named("second")
    public Connection getConnection(@Named("second") TransactionalShell txShell) {
        return ((JdbcTransactionalShell) txShell).getConnection();
    }

    /**
     * Optionally produce the data source from second TxShell
     */
    @Unscoped
    @Named("second")
    public DataSource getDataSource(@Named("second") TransactionalShell txShell) {
        return ((JdbcTransactionalShell) txShell).getDataSource();
    }

}
----

== Examples

See full source code in the framework source code section #examples/jdbc-example#


