= JDBI integration module

This module provides an ability to use JDBI within services via the "Handle" injection.
It is also provides a local transaction management support with the TransactionalShell implementation.

Typical usage:

.MyService.java
[source,java]
----
@Service
public class MyService {

    private final Provider<Handle> handleProv;

    @Inject
    public MyService(Provider<Handle> handleProv) { <.>
        this.handleProv = handleProv;
    }

    @Transactional
    public String readFromDB() {

        return handleProv.get()  <.>
                  .createQuery(...)
                  .bind(...)
                  .mapTo(String.class)
                  .first();

        // No need to close handle
    }
}
----

<.> Inject handler provider
<.> Obtain attached to a transaction Jdbi Handle

== Simple usage

In case of a single jdbi instance usage just define _hikari.properties_ file:

.config/hikari.properties or META-INF/hikari.properties
[source,properties]
----
driverClassName=...
jdbcUrl=jdbc:...
----

Optionally create custom jdbi options class extends JdbiOptionsPrototype.
This class can be used for jdbi extra configuration.
Application can have multiple separate JdbiOptions classes.

.JdbiOptions.java
[source,java]
----
@Config
public class JdbiOptions extends JdbiOptionsPrototype {

    @Override
    public void applyOptions(Jdbi jdbi) {
        // Apply configuration to jdbi instance
    }
}
----

== Multiple jdbi instances

To use multiple jdbi instances use a custom configuration for each extra jdbi handle connected to different DB.

1) Define extra hikaricp configuration class:

.ExtraHikariProperties.java
[source,java]
----

@Config
public class ExtraHikariProperties extends HikariProperties {
    @Override
    protected String getFileName() {
        return "extra-hikari.properties";
    }
}

----

2) Fill in extra-hikari.properties:

.config/extra-hikari.properties or META-INF/extra-hikari.properties
[source,properties]
----
ataSourceClassName=org.postgresql.ds.PGSimpleDataSource
username=user
password=password
jdbcUrl=jdbc:postgresql://...
----

3) Create extra jdbi configuration classes that extends AbstractJdbiConfig (or JdbiConfigPrototype).
This config will be used to provide the DataSource and apply JdbiOptions to the Jdbi instance.

.ExtraJdbiConfig.java
[source,java]
----
@Config
public class ExtraJdbiConfig extends AbstractJdbiConfig {

    @Inject
    public CustomJdbiConfig(

            // Jdbi will use user defined extra hikaricp data source
            @Classed(ExtraHikariProperties.class) DataSource dataSource,

            // Optional configurations will be applied to the jdbi instance.
            @Classed(ExtraJdbiConfig.class) Polysupplier<JdbiOptionsPrototype> options) {

        super(dataSource, options);
    }
}
----

4) Define appropriate producer to produce TransactionalSnell and Handle bound to extra jdbi instance

.ExtraJdbiProducer.java
[source,java]
----
@Producer
public class ExtraJdbiProducer {

    /**
     * Produce extra transactional shell to control transactions.
     */
    @Singleton
    @Named("extra")
    public TransactionalShell getTxShell(@Classed(ExtraJdbiConfig.class) Jdbi jdbi) {
        return new JdbiTransactionalShell(jdbi);
    }

    /**
     * Produce extra handle providing from extra transactional shell
     */
    @Unscoped
    @Named("extra")
    public Handle getHandle(@Named("extra") TransactionalShell txShell) {
        return ((JdbiTransactionalShell) txShell).getHandle();
    }

}
----

Inject extra jdbi handle with @Named annotation

.MyService.java
[source,java]
----
@Service
public class MyService {

    private final Provider<Handle> handleProv;

    @Inject
    public TheService(@Named("extra") Provider<Handle> handleProv) {
        this.handleProv = handleProv;
    }

    @Transactional(shell="extra")
    public String readFromDB() {
        return handleProv.get()....
    }
}
----

== Examples

See full source code in the framework source code section #examples/jdbi-example#


