[[intro]]

= Colesico-Service

Services are the basic essence of representing business logic in applications.
It provides the opportunity for various automation for business logic beans, (weblets,
restlets and others built on their basis. For example, they provide support for
transaction management, support for remote methods invocations, interceptors.

Services is a regular POJOs with @Service annotation.

Simple service example:

[source,java]
----
@Service
public class MyService {

    @Transactional
    public Boolean save(String value) {
        ...
    }

}
----

Services are integrated to the IoC  (Dependency Injection module).
There is no need to declare an IoC producer to use service beans in the context
of dependency injection. Service is singleton by default. But their scope can be
redefined using the appropriate annotations (@ThreadScoped , etc)

To automate the service beans the framework uses code generation  at the compilation stage.
It creates a proxy classes that extends service classes.

== Service methods

By default, the service methods that the framework instrumentates are all public methods of the service bean.
To instrumentate a protected method,  use the @ServiceMethod annotation (on method or class).
To exclude method from instrumentation  use the @PlainMethod annotation.

== Self method invocation

Unlike EJB beans, calling your own instrumentated methods can be performed directly using this.methodToCall()
without injection bean to itself.

== Remote methods invocation

The following annotations are used to configure a remote methods call:

* @LocalMethod - exclude method from remote call
* @Compount - to declare bean as a set of separate parameters  (each bean field - separate parameter)
